# Generated by Django 5.1.7 on 2025-03-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Thời hạn hoàn thành', null=True),
        ),
    ]
